### PR TITLE
#3 :sunny: i18n link: partial fix for this bug.

### PR DESCRIPTION
**Pull request by SalahAdDin**
This solve partially this bug, but we have problem with the next files:

In `jquery-ui/i18n/datepicker-`:
seleccion_100

in `jquery-ui-timepicker/i18n/jquery.ui.timepicker-`:
seleccion_101

In `select2/js/i18n/`:
seleccion_102

All these files have a full language_code name file and using `slice` for trim the `language_code` setting browser can not get this full url.

I'm thinkg about add other `if` for this files without slice language code setting.

Please help me and don't merge yet.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Consider that this plugin is oudated, so, can we change by other?

**Comment by SalahAdDin** [comment]
Select2 ever update, so, no problem with it.

**Comment by SalahAdDin** [comment]
Ok: we have a  problem with this because i'm not sure about use `slice`i these way.

**Comment by SalahAdDin** [comment]
What's about this? https://github.com/felicegattuso/datedropper
The problem will be configurate localization language.

**Comment by SalahAdDin** [comment]
For change the `jQuery` modules we ca find the next function in `static/jet/js/main.js`: 
```javascript
var initDateTimeWidgets = function() {
            var removePreviousSibling = function($element) {
                var node = $element[0].previousSibling;
                node.parentNode.removeChild(node);
            };

            var djangoDateTimeFormatToJs = function(format) {
                return format.toLowerCase().replace(/%\w/g, function(format) {
                    format = format.replace(/%/,"");
                    return format + format;
                });
            };

            var updateDatetimeLayout = function() {
                $('.form-row .datetime').each(function () {
                    var $dateTime = $(this);
                    var $dateField = $dateTime.find('.vDateField');
                    var $timeField = $dateTime.find('.vTimeField');

                    removePreviousSibling($dateField);
                    removePreviousSibling($timeField);

                    $dateField.nextAll('br').first().remove();
                });
            };

            var initDateWidget = function() {
                $('.form-row .vDateField').each(function () {
                    var $dateField = $(this);
                    var $dateLink = $('<a href="#">').addClass('vDateField-link');
                    var $dateButton = $('<span>').addClass('icon-calendar');

                    $dateLink.append($dateButton).insertAfter($dateField);

                    $dateField.datepicker({
                        dateFormat: djangoDateTimeFormatToJs(DATE_FORMAT),
                        showButtonPanel: true,
                        nextText: '',
                        prevText: ''
                    });
                    $dateLink.on('click', function (e) {
                        if ($dateField.datepicker('widget').is(':visible')) {
                            $dateField.datepicker('hide');
                        } else {
                            $dateField.datepicker('show');
                        }

                        e.preventDefault();
                    });
                });

                var old_goToToday = $.datepicker._gotoToday;
                $.datepicker._gotoToday = function(id) {
                    old_goToToday.call(this,id);
                    this._selectDate(id);
                };
            };

            var initTimeWidget = function() {
                $('.form-row .vTimeField').each(function () {
                    var $timeField = $(this);
                    var $timeLink = $('<a href="#">').addClass('vTimeField-link');
                    var $timeButton = $('<span>').addClass('icon-clock');

                    $timeLink.append($timeButton).insertAfter($timeField);

                    $timeField.timepicker({
                        showPeriodLabels: false,
                        showCloseButton: true,
                        showNowButton: true
                    });
                    $timeLink.on('click', function (e) {
                        if ($timeField.datepicker('widget').is(':visible')) {
                            $timeField.datepicker('hide');
                        } else {
                            $timeField.timepicker('show');
                        }

                        e.preventDefault();
                    });
                });
            };

            updateDatetimeLayout();
            initDateWidget();
            initTimeWidget();
        };
```

**Comment by JensAstrup** [comment]
I'm a huge fan of Material design, so I vote for tha tone

**Comment by SalahAdDin** [comment]
We have to minify javascript files also, please remember me it.

**Pull request merged**
